#!/bin/bash

source common/flow/scripts/project_flow.sh

export PROJECT_NAME="WEB_SDR"
export PROJECT_ROOT=$(pwd)

create_var_project $PROJECT_ROOT $PROJECT_NAME

echo "Liste des variables :"
set | grep $PROJECT_NAME